### PR TITLE
Issue 345

### LINKED ISSUE #343: Fix snaps-hcp alerting
snaps-hcp WS calls have broken

### LINKED ISSUE #345: OpenDistro Elasticsearch failure for invoking aggAttack

### PR DESCRIPTION
**Pull request by akadam**
#### Questions:
- Have you connected this PR to the issue it resolves? Yes
- Does the documentation need an update? No
- Does this add new dependencies? No
- Have you added unit or functional tests for this PR? No

### CODE REVIEW

**Comment by akadam** [comment]
Run Tofino aggregate build

**Comment by akadam** [comment]
Run Tofino Environment Build

**Comment by akadam** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Review by spisarski — APPROVED** [review]
Changes look reasonable and should not interfere with CI. Feel free to merge once CI completely passes. (I just kicked off the tofino lab job again)

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Pull request merged**
