### PR TITLE
Scripts to startup a Siddhi P4 Telemetry report runtime

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixex #397 

Installs everything required to begin running the Siddhi replacement for the SimpleAE

#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
run env_build terraform script with the following additional arguments:
-var env_type=siddhi
-var create_ami=no
-var ubuntu_version=20

#### Any background context you want to provide?\
The SimpleAE needs a major upgrade
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? probably
- Does this add new dependencies? not really
- Have you added unit or functional tests for this PR? sorta

### CODE REVIEW

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino core build

**Pull request merged**
