### PR TITLE
Added ansible script to load index patterns 

### LINKED ISSUE #309: AE: Export index pattern from Kibana.
As discussed Wed Nov 4th

### PR DESCRIPTION
**Pull request by akadam**
Fixes #309 
What does this PR do? Automates loading index patterns in AE using ansible
Do you have any concerns with this PR? No
How can the reviewer verify this PR?
Any background context you want to provide? No
Screenshots or logs (if appropriate) No
Questions:
Have you connected this PR to the issue it resolves? Yes
Does the documentation need an update? No
Does this add new dependencies? No
Have you added unit or functional tests for this PR? No

### CODE REVIEW

**Comment by akadam** [comment]
Run Tofino Environment Build

**Comment by akadam** [comment]
Run Tofino aggregate build

**Comment by akadam** [comment]
Run Tofino lab trial build

**Review by spisarski — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Pull request merged**
