### PR TITLE
Ci linters

### LINKED ISSUE #28: Validate Ansible yml file ci
Check the ansible playbooks are formatted correctly and don't have syntax errors.

https://github.com/ansible/ansible-lint

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #28 By changing the ansible playbooks so they can pass ansible-lint
#### Questions:
- Have you connected this PR to the issue it resolves? Fixes #28 and is also associated with #102 & #29 
- Does the documentation need an update? no
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? no

### CODE REVIEW

**Comment by bo-quan** [comment]
Can one of the admins verify this patch?

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Pull request merged**
