### PR TITLE
Tcp testing

### LINKED ISSUE #301: Exercise TCP packets in lab_trial
Create tests to ensure two-way communication between host1 & inet (one host NB of core)

### LINKED ISSUE #317: Add arping and iperf3 to Centos 7 hosts
When our automated tests run against Centos 7 hosts, they fail as arping and iperf3 are not being installed as arping currently it is for Ubuntu. Now that we are considering making our internal lab_trial hosts Centos, we should ensure that our host setup scripts add the arping via the yum block.

Also add iperf3 to ubuntu hosts too.

@Sanjhana-Jayagopal , This will be exercised with our current automation scripts as the snaps-hcp machine will be getting setup with the same playbook.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #301 and Fixes #317 
Ensures that paths have been properly discovered and TCP packets can flow properly through the system.

Please note that new test cases other than "all" can be run now without extra-vars.
all-data-drop - runs data drop test scenarios
add-data-forward - runs data forward test scenarios
all-data-inspection - runs data inspection test scenarios
all-pkt-flood - runs packet flood test scenarios
iperf - runs iperf test scenarios
restart_services - restarts all TPS services (tps-tofino-model (aggregate & core), tps-tofino-switchd (aggregate & core) but does not reconfigure the environment, tps-tofino-sdn (controller)
discover-paths - Configures the environment for testing
restart - restarts services and reconfigures paths

#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
Ensure CI runs to completion
#### Any background context you want to provide?
We can now really test these switches with real network load.
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? not really at this time
- Does this add new dependencies? I've added arping to centos images and iperf to both Ubuntu & Centos
- Have you added unit or functional tests for this PR? yes, iperf integration tests

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino Environment Build
Run Tofino aggregate build
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Pull request merged**
