### PR TITLE
Created tests to exercise the SimpleAE running on the snaps-hcp machine

### LINKED ISSUE #275: Activate tofino-build CI job on Jenkins
Activate and test the existing job for building tofino AMIs

### LINKED ISSUE #280: Run full integration tests with SimpleAE for lab_trial TNA
Before creating scenarios that Cox laid out for us, we need snaps-hcp running. So for integration testing with an AE, this ticket will create tests to exercise the SimpleAE for the time being.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #280
Attempts to addresses (#275) as that job will be tested by this PR

Adds new tests that exercise the SimpleAE as running on the snaps-hcp (centos) machine.

#### Do you have any concerns with this PR?
This PR will break the CI for lab_trial running on Mininet. We are now beginning to deprecate our mininet/v1model implementations and prior to this PR I have deactivated the mininet lab_trial and mininet environment build Jenkins jobs.
#### How can the reviewer verify this PR?
ensure CI passes (however, tofino-build may fail as it just was reactivated and may need to be deactivated again)
#### Any background context you want to provide?
Just another step towards building our lab_trial virtual environment to be closer to the Cox hardware environment
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? not really, but we may have to start removing the mininet docs later.
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? yes, new integration tests for lab_trial

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino Build

**Comment by spisarski** [comment]
Run Tofino Build

**Comment by spisarski** [comment]
Run Core Tests

**Comment by spisarski** [comment]
Run Tofino Build

**Comment by spisarski** [comment]
Run Tofino Build

**Comment by spisarski** [comment]
Run Tofino Build

**Comment by spisarski** [comment]
Please ignore the "Jenkins CI - env-build Tofino" CI failure. The Jenkins host requires some maintenance.

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Pull request merged**
