### PR TITLE
Expanding data-drop tests to validate multiple reports

### LINKED ISSUE #354: Ensure drop reports for every data_drop_t entry gets created.
While working on the SimpleAE for ingesting TRPTs, I noticed that it appears that we are only processing the first data_drop_t entry rather than all of them. Currently our only test around drop reports only uses a single entry into that table. We should expand those tests while fixing the issue.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #354 
 Ensures that the controller is emitting drop reports for each entry in the data_drop_t table.
#### Do you have any concerns with this PR?
No
#### How can the reviewer verify this PR?
Ensure CI passes
#### Any background context you want to provide?
The previous drop report tests were only performed with one table entry
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? no
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? Improved the existing drop report tests

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Pull request merged**
