### PR TITLE
Fix SDN Controller

### LINKED ISSUE #400: Fix SDN controller
SDN controller is currently broken and this appears to be occurring while it tries to create the web services. This appears to be due to changes on PyPi as we had not pinned the flask library versions.

### LINKED ISSUE #401: Tofino build is broken
Tofino build will no longer complete. Try taking a look at any recent changes within 2021 to the upstream dependencies.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #400 & Fixes #401
Pinned the Flask python libraries as the latest updates have broken the SDN Controller.
Added additional logging and error handling.
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
ensure CI passes
#### Any background context you want to provide?
Flask had a big 2.0 release this year and we have not really executed these CI jobs since January.
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? no
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? no

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino core build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Pull request merged**
