### PR TITLE
Add new optional int_switch_id switch attribute

### LINKED ISSUE #271: Create optional switch ID to be used for INT data.
As the device-id for the tofino switches will be 0 in all cases, we should create another optional value to place into the topology that can be used for the switch_id that is being inserted into the INT headers.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #271 
Adds new optional int_switch_id member to the switch object and topology that will default to the "id" field when it doesn't exist.
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
Check the centos@ae:/var/log/transparent-security files generated by receive_packets after running the lab_trial/TNA tofino automation tests to ensure non of the switch_id values being read from these packets do not have any with the value '0'
#### Any background context you want to provide?
When running P4 on Tofino, the device ID of each program on each switch VM is always 0 and really should only be used for obtaining the GRPC socket connection. For backwards compatibility, we will be defaulting to the old 'id' value when 'int_id'
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? I do not believe so
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? no, but we really should add validation for these values.

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Please ignore the env-build Tofino failure

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Pull request merged**
