### PR TITLE
Implemented TNA Register in core_tna.p4 for sampling of Telemetry Reports

### LINKED ISSUE #153: Add support for sampling rate for INT-MD Telemetry Reports
In core.p4, we are currently sending a telemetry report for every packet. As per the Telemetry Report specification, we should implement a means in P4 to output 1 out of every n packets where n is a configurable non-negative integer.

### PR DESCRIPTION
**Pull request by spisarski**
Fixes #153 

#### What does this PR do?
Implements a TNA extern called a "Register" where we can keep track of each potential packets to mirror so we can configure the "mirror_sampler" register to mirror out every or on in every nth packet for generation of Telemetry Reports.
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
If the data-inspection tests are run and the TpsCoreIngress.mirror_sampler table's "rate" field has a value other than 0, the tests that count packets on the "clone" machine will fail. If the "rate" is '1', every other packet will be mirrored, '2', every third, etc.
#### Any background context you want to provide?
We need this functionality for the lab trial as the Telemetry Reports could overwhelm the network and AEs under load.
#### Questions:
- Have you connected this PR to the issue it resolves? yes #153
- Does the documentation need an update? Eventually, but only after we address #328
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? no, see #328

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Pull request merged**
