### PR TITLE
Drop report hash functionality

### LINKED ISSUE #310: AE: Parse drop report and correlate to determine when attack has stopped.
Display number of dropped packets.

### LINKED ISSUE #343: Fix snaps-hcp alerting
snaps-hcp WS calls have broken

### PR DESCRIPTION
**Pull request by akadam**
Fixed #343 
Added drop report hash functionality using SHA256
#### Questions:
- Have you connected this PR to the issue it resolves? Yes
- Does the documentation need an update? No
- Does this add new dependencies? No
- Have you added unit or functional tests for this PR? No

### CODE REVIEW

**Comment by akadam** [comment]
Run Tofino lab trial build

**Comment by akadam** [comment]
Run Tofino Environment Build

**Review by spisarski — APPROVED** [review]

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Pull request merged**
