### PR TITLE
Tna lab trial

### LINKED ISSUE #194: Enable lab_trial tests for tofino
Environment ready, just need to figure out what's different between tofino and mininet
Related to the epic #170

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #194 
Enables the running of the lab_trial scenario tests on Tofino/TNA
#### How can the reviewer verify this PR?
Manually run the lab_trial TNA tests. Will be addressing #266 after this has been merged
#### Any background context you want to provide?
We should be able to deploy to hardware now...
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? no
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? no

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Please ignore the Tofino Core and Lab Trial failing jobs. There appears to be an issue on the CI machine causing these two new jobs to fail. I have personally validated that all of the tests have completed successfully.

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Review by Sanjhana-Jayagopal — APPROVED** [review]

**Pull request merged**
