### PR TITLE
Ensure L2 routing for IPv6 hosts

### LINKED ISSUE #315: Add IPv6 support for NDP (similar to IPv4 ARP)
Currently we are only discovering the path with IPv4 arping calls and this is causing the -dip4 argument to be leveraged for ARP table lookups. If we had IPv6 support, we should be able to get rid of that arg from both send_packets.py & receive_packets.py.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #315 
Manually added neighbor entry (IPv6 equivalent to ARP) to ip dev switch tunnel for IPv6 L2 ipv6_routing
Removed -dip4 hook for destination MAC lookups (send_packets.py) and interface (receive_packets.py) in the test code. Now lookups are ocurring using the destination IP address from ARP cache for IPv4 & using get-mac library getmac.get_mac_address() for IPv6. 
Fixed IPv6 addresses in lab_trial topology (inet & host2 had same & ae was in a different subnet)

iperf3 will now work with IPv6 endpoints
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
Ensure CI doesn't fail
#### Any background context you want to provide?
Need to ensure IPv6 works like IPv6
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? no
- Does this add new dependencies? Python - get-mac
- Have you added unit or functional tests for this PR? Updated the existing to reflect changes as well as added an additional call on the test client to IPv6 endpoints in the iperf.yml test case

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino core build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino core build

**Review by akadam — APPROVED** [review]

**Pull request merged**
