### PR TITLE
Issue 410 housekeeping

### LINKED ISSUE #410: Cleanup old mininet and other old artifacts that no longer work
Remove the old chaff.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #410 
Took the Marie Kondo method of tidying to this repo and removed any file that did not add to the things that are currently working.
#### Do you have any concerns with this PR?
no, I created a tag branch named "siddhi-ae" prior to working on this.
#### How can the reviewer verify this PR?
Ensure that I didn't break CI
#### Any background context you want to provide?
We'd like to wrap a bow around the project and feel like removing old stuff we thought we may need at the time would be a good way for one to get their head around the project after it has been shelved for awhile.
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? yes, but I will take care of that with issues #411 & #412
- Does this add new dependencies? actually removes some...
- Have you added unit or functional tests for this PR? no, actually removes a bunch of old ones not being executed by CI

### CODE REVIEW

**Comment by spisarski** [comment]
Run Linter

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino Environment Build

**Review by chriscorcimiglia — APPROVED** [review]

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Pull request merged**
