### PR TITLE
Issue 349

### LINKED ISSUE #349: Combine AE UDP and TCP pipelines

### PR DESCRIPTION
**Pull request by akadam**
Combines TCP and UDP pipeline
#### Questions:
- Have you connected this PR to the issue it resolves? Yes
- Does the documentation need an update? No
- Does this add new dependencies? No
- Have you added unit or functional tests for this PR? No

### CODE REVIEW

**Comment by akadam** [comment]
Run Tofino Environment Build

**Comment by akadam** [comment]
Run Tofino lab trial build

**Comment by spisarski** [comment]
Run Tofino aggregate build

**Review by spisarski — APPROVED** [review]

**Comment by akadam** [comment]
Run Tofino Environment Build

**Comment by akadam** [comment]
Run Tofino aggregate build

**Comment by akadam** [comment]
Run Tofino lab trial build

**Comment by akadam** [comment]
Run Tofino aggregate build

**Comment by akadam** [comment]
Run Tofino lab trial build

**Comment by akadam** [comment]
Run Tofino Environment Build

**Comment by akadam** [comment]
Run Tofino lab trial build

**Pull request merged**
